### PR TITLE
Merge efforts back to source

### PR DESCRIPTION
**Pull request by Tuxified**
Hi,

I slowly made some progress and was wondering what your thoughts are? Do you want to keep wingyplus/tree-sitter-elixir as the canonical source for Tree-sitter Elixir? Perhaps you also had a completely different approach in mind?

### CODE REVIEW

**Comment by wingyplus** [comment]
Hi @Tuxified, 

First of all, I want to thank you for interesting in this project and spending effort on it. I will ​take a look at it in detail on weekend.  :)

**Comment by wingyplus** [comment]
@Tuxified That's looks very good!! :) I'm glad to merge this PR. I've another question want to ask you, do you want to be a maintainer of this project? I'll add you to contributor if you want to.

**Comment by Tuxified** [comment]
Glad to hear you like it so far. To answer your question: yes it'd also like to maintain this project. I think we should then update or remove my fork so it's clear to folks that this repo is the canonical one (as some folks have already started forking my repo).

Next to our efforts I've also stumbled upon https://github.com/ananthakumaran/tree-sitter-elixir, which seems to take & different approach and already can parse all of elixir-lang/elixir, so perhaps we can merge efforts into 1 repo/package etc ? I already took the liberty to ask what their plans are and they seem to align (have a package which can be used by everyone).

What are your thoughts ? Would you like to keep working on our version or something else ..

**Comment by wingyplus** [comment]
@Tuxified I would like to keep our version until we’re all agree to merge the grammar into 1 repository. :)

**Comment by wingyplus** [comment]
@Tuxified I invited you to this repository. If you didn’t receive invitation, please mention me in this PR or send a DM to elixirforum. :)

And finally, I merge this PR to lets this effort move forward.

Thanks for your effort. :)

**Pull request merged**
